export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  profile: "/profile",
  profileById: (id: string) => `/profile/${id}`,
  artist: (id: string) => `/artist/${id}`,
  album: (id: string) => `/album/${id}`,
  playlists: "/playlists",
  playlist: (id: string) => `/playlists/${id}`,
  library: "/library",
  settings: "/settings",
  notifications: "/notifications",
  artistDashboard: "/artist/dashboard",
  adminDashboard: "/admin",
  adminTickets: "/admin/tickets",
  adminArtists: "/admin/artists",
  adminAccounting: "/admin/accounting",
  adminPricing: "/admin/pricing",
} as const;
